### ISSUE TITLE
New Rails features and how to use them 

### ISSUE THREAD

**Issue by kestlund** [projecthydra-labs/hydra-connect#107]
ActionCable, Rails 5's JS integration with React, ActiveJob and other newer features under Samvera

Presenter: Rob Kaufman

_Submitted via Google Form_

**Comment by orangewolf** [comment]
@kestlund - ok, so I wasn't sure exactly how much detail you wanted and I may have gotten a little verbose.  Feel free to edit down anything you want, let me know if I missed anything, or to just say "Hey Rob, do this again" or whatever.

--
**Goals and Outline**
Rails, the framework that Samvera is based on continues to march forward rapidly.  Best practices and features change with each release continuing to make the platform better (or at least different 😉).  This workshop will go through details of some of the latest changes in recent Rails versions including ActiveJob, creation of better parent objects, the attributes API and a slew of Javascript related changes including webpack integration and what it means for the future of Javascript in Rails applications.  Along the way we'll discuss changes to best practices in the broader community and how they affect your existing and new apps.  We'll do lots of live examples and get into implementation details.  This workshop will be divided into 3 parts for participant convenience.  Parts 2 and 3 are hands on, so please bring a laptop with Virtual Box installed.  We'll distribute a VM to make sure that everyone is getting a uniform experience. 

Part 1 - Feature Overview. We'll discuss the various features and what each might be used for in the context of a Samvera app. This short pre-section will be good for those staying for the rest of the workshop, but will also be accessible to non-technical folks interested in the kinds of changes the Rails core team are making. That's right, you can bring your manager and we won't even make fun of them if they leave early.

Part 2 - Backend features. Here we'll dive into some changes to inheritance and what they mean for our models, go over the details of ActiveJob and touch on Rails 5.1 System Tests.

Part 3 - Frontend features. We'll hit the highlights of React and how to use have React widgets in your Samvera apps.  We'll look at issues around mixing React and jQuery and talk through strategies for dealing with themthat. We'll also talk about Turbolinks, when you want Turbolinks vs React Router, and how Turbolinks plays with other JS frameworks.  Lastly we'll cover ActionCable: and how to and when to use websockets in your application and how to connect that to the other JS components we talked about.

**Who is this for?**
Primary audience will be developers, ideally with at least some Samvera or Rails experience.  Those without such experience are encouraged to come to Part 1 and should feel free to decide if staying for part 2 and 3 is the right optionthing for them.

**Who is giving this workshop?**
Rob Kaufman is a developer based out of San Diego.  He founded Notch8 in 2007 to help provide businesses and institutions with the development resources they need.  He has been working with Ruby since 2003 and has experience with almost every version of Rails since 0.10.2.  Rob is excited to be joining the Samvera community and has had the Notch8 team ramping up on various Samvera projects over the last 18 months. Notch8 has helped teams with Samvera apps work on both development and deployment.

**Supplies Needed**
Please bring a laptop with VirtualBox installed.  We'll have a VM available via thumb drives for those attending the workshop which we'll use to bring everyone to the same system setup quickly.
