### ISSUE TITLE
Metadata management and batch ingest automation with Git/GitHub, Jenkins, Ansible, and JIRA

### ISSUE THREAD

**Issue by jcoyne** [projecthydra-labs/hydra-connect#119]
Metadata management and batch ingest automation with Git/GitHub, Jenkins, Ansible, and JIRA

Suggested by: Alex Dunn and Chrissy Rissmeyer
Presenter: Alex Dunn and Chrissy Rissmeyer
Format: Presentation
Audience: Devs, Metadata

**Comment by dunn** [comment]
1. Alex Dunn (UCSB), Chrissy Rissmeyer (UCSB)
2. Remove “Ansible” from title
3. Several years ago UCSB incorporated Git/GitHub and JIRA into our metadata management and batch ingest workflows. Since then we’ve looked at repurposing other development tools to provide lightweight and automated solutions to problems we often face. One is that we rely primarily on batch ingests when adding content to our Samvera repository. As a result it’s especially important for the metadata to be error-free; it’s not fun to have an ingest fail overnight and spend the morning tracking down why. Programmatically testing and validating digital object metadata prior to ingest helps us avoid these failures. The metadata itself is managed by Git and stored in GitHub; this allows us to run automated checks against any changes using Jenkins and some custom libraries we’ve written for validating CSV and MODS metadata. In this session, we will provide an overall of our current ingest preparation workflow and the tools we are using, and will discuss some of the benefits that have come out of this collaborative effort.
4. Intermediate; metadata/dev
