### ISSUE TITLE
Extending Fedora: API-X and Import/Export

### ISSUE THREAD

**Issue by jcoyne** [projecthydra-labs/hydra-connect#121]
Extending Fedora: API-X and Import/ExportHands-on with new Fedora extensions and tools

Suggested by: David Wilcox
Presenter: David WilcoxAndrew Woods
Format: Workshop
Audience: Developers, Metadata

**Comment by dwilcox** [comment]
Here is a detailed description of the workshop:

Fedora is the flexible, extensible, open source repository platform that commonly underlies Samvera implementations. Fedora provides a number of core services that Samvera already uses, such as CRUD operations, versioning, and fixity, and several new, potentially useful extended services have been introduced within the last year. The API Extension Framework provides a means of binding services to repository objects in order to extend the functionality of Fedora, while the Import/Export Utility makes it easier to get content into and out of Fedora in standardized formats and packages. This workshop will introduce both of these new services and discuss how they might be used in the context of Samvera. Participants will also have an opportunity to try them out via hands-on exercises in combination with a virtual machine.

Participants should bring a laptop with at least 4GB of RAM to run the virtual machine. Instructions will be provided in advance, and copies of the VM will also be available on USB drives at the workshop.
