### ISSUE TITLE
Dive into GeoConcerns : Hands-on exercises with GeoConcerns, a PCDM-based Fedora...

### ISSUE THREAD

**Issue by lsat12357** [projecthydra-labs/hydra-connect#13]
Dive into GeoConcerns : Hands-on exercises with GeoConcerns, a PCDM-based Fedora 4 reference implementation for geospatial resources in a repository.

Suggested by: Darren Hardy
Presenter: Eliot Jordan, Darren Hardy
Format: Workshop - half day
Audience: Managers, developers

**Comment by richardGreen** [comment]
2016-07-06

Yes, we’re planning to give this “Dive into GeoConcerns” workshop. It would be a half-day (3 hrs including a break). We require laptops with VirtualBox and Vagrant installed to follow along with the workshop — we will provide instructions beforehand if we can get an email list of participants; otherwise, they can do the installations at the workshop. We’ll work on (b) and get back to you.

**Comment by richardGreen** [comment]
2016-07-29
This workshop focuses on hands-on exercises with GeoConcerns, a new PCDM-based Fedora 4 reference implementation for geospatial resources in a repository (see http://geoconcerns.github.io), and we welcome developers and managers alike to participate. These exercises will include modeling content in Fedora 4 using Hydra’s PCDM data model. Furthermore, participants will install and configure the GeoConcerns software on their laptops, and learn how to structure and “wrangle” geospatial data for ingest.

We will discuss how to develop scaleable and sustainable digital repository services for geospatial resources using open, collaborative approaches. Participants will learn about data modeling and metadata requirements for curation of a wide-variety of geospatial content types, including historic scanned maps, vector data, raster data, and georectified maps. The instructors contribute to open source communities, including OpenGeoMetadata, GeoBlacklight, and Hydra, and have practical experience building production-quality geospatial repository services.
