### ISSUE TITLE
How to Write Module-Based JavaScript with RequireJS and the AMD (Asynchronous Module Definition) Pattern

### ISSUE THREAD

**Issue by jcoyne** [projecthydra-labs/hydra-connect#133]
How to Write Module-Based JavaScript with RequireJS and the AMD (Asynchronous Module Definition) PatternTired of worrying about load order for your script includes? Tired of polluting the global namespace? Want to write more re-usable JavaScript code with discrete modules? Maybe RequireJS / the AMD pattern is right for you! This presentation will go through the construction of a simple RequireJS-based JavaScript app with a few modules. A general familiarity with JavaScript is recommended.

Suggested by: Eric O'Hanlon
Presenter: Eric O'Hanlon
Format: Presentation / maybe workshop?
Audience: Devs

**Comment by elohanlon** [comment]
Updated description below:

Title: How to Write Module-Based JavaScript with RequireJS and the AMD (Asynchronous Module Definition) Pattern

Description: Tired of worrying about load order for your script includes? Has global namespace pollution got you down? Have you ever accidentally clobbered existing variables or functions by redeclaring them in other files?  Do you want to write more re-usable, maintainable JavaScript by structuring your code in discrete modules?  If your answer to some/all of these questions is yes, then maybe RequireJS / the AMD pattern is right for you!

This workshop will go through the construction of a simple RequireJS-based JavaScript app with a few modules. Some experience with JavaScript is recommended, and a laptop is highly recommended because you will be writing code.  Workshop materials (in the form of download links) will be supplied before the workshop begins.

Suggested by: Eric O'Hanlon
Presenter: Eric O'Hanlon
Format: Half Day Workshop
Audience: Devs
Time: Afternoon of Monday, November 6th
