### ISSUE TITLE
Intro to Hyrax

### ISSUE THREAD

**Issue by kestlund** [projecthydra-labs/hydra-connect#166]
Description needed

**Comment by bess** [comment]
About the workshop:
In this workshop we will walk through a local installation of Hyrax 2.x, generate a work type, and get a local test suite running. This will be an abbreviated version of a module usually run at Samvera Camp. Because of the limited time, this will mostly be a demo with audience participation. However, we will offer some support if you want to bring your laptop and follow along.

About Bess Sadler, Senior Developer, Data Curation Experts:
Bess has been building digital repositories for over fifteen years. She is a co-founder of both the Blacklight and Samvera software projects, and is a passionate advocate for open source software and DevOps culture.
