### ISSUE TITLE
Technical On-Boarding - discussion of how to contribute code at the community le...

### ISSUE THREAD

**Issue by lsat12357** [projecthydra-labs/hydra-connect#24]
Technical On-Boarding - discussion of how to contribute code at the community level including such topics as: commonly used architecture patterns, expectations/suggestions for pull request size, determining the level of the gobstopper at which certain types of work should be implemented, etc.

Suggested by: Steve Van Tuyl, Josh Gum, Brandon Straley, Gregorio Luis
Presenter: ?  
Format: Workshop?
Audience: Developers who are planning/interested in participating in community-level dev efforts + interest to managers

**Comment by richardGreen** [comment]
Maybe not a workshop - presentation.  Follow up.  Oregon State folks...

**Comment by richardGreen** [comment]
2016-06-07

Hi Folks, 

So, to try to clarify: the reason we submitted this session proposal was because, as relative newcomers to doing development at the “community level” (on a recent stretch of work related to works-in-works functionality for CC/Sufia), we found it difficult to fully comprehend the expectations and process for contributing. As you may know, many of the core contributors in the hydra world have been participating for a while, and it seems that there is a general lack of technical on boarding for newcomers beyond a “trial by fire” approach. 

The session we had in mind would probably be best described as a breakout group to discuss whether and how to provide support for technical on boarding. It is entirely possible, for example, that our experience is unique, but I doubt it. It would be helpful if one or more hydra developer veterans could lead or co-lead. 

Thoughts? Feedback?

Thanks. 

steve

**Comment by escowles** [comment]
I think a breakout session to talk about how we support on-boarding would be good — but a workshop to actually help on-board new people would be even better.

**Comment by richardGreen** [comment]
2016-07-13 from EC: I'd be happy to present this workshop if it doesn't conflict with the PCDM workshop.  If it does conflict, there are several other people who are well-versed in the process who could be good presenters:

Mark Bussey
Justin Coyne
Trey Pendragon
Mike Giarlo
Adam Wead
Hector Correa

Even if I'm not presenting, I can help develop the content.  I've asked Steve Van Tuyl for some feedback on what things were surprising or mysterious as they engaged with community development as a starting place for important things to cover.

I would expect this to be a half-day workshop.

Reply: Thanks for the very full reply and your offer of help!  If there's a full day PCDM workshop then inevitably there will be a clash.  The Program Committee will discuss this possible workshop again next Tuesday and I'll be back in touch.

**Comment by mark-dce** [comment]
I would second EC's proposal and love to see us get a module / workshop in a Dive-into-Hydra format that could be used at Conferences, Hydra Camp, or Online, that walks new developers through their first commit:
- What's a CLA and why do I need one
- What does squashing commit's mean
- Why does my code need tests (AKA why did my Pull Request get rejected)
- Where do I get help (how do all the different communication channels work - where should I try first)

etc.

count me in for helping develop or present content.

**Comment by richardGreen** [comment]
2013-07-22
Esmé

Further to the emails below.  The Program Committee would be very grateful if you would help develop the content for this half-day workshop (Mark says he's willing to help) and, hopefully, lead it.  As things stand right now, this workshop is pencilled in for the morning and PCDM for the afternoon - so no clash.  You might want to think about a co-presenter (or two).  I'm hoping that Mark will part-lead one of the other morning workshops and Adam is likely to be tied up before the coffee break, but Justin, Trey, Mike and Hector look as though they have no formal commitments.

As well as your agreement to lead, I'd be very grateful for an outline of this workshop before the end of next week because we hope to publish the workshop timetable, with descriptions, at the end of the month.  Also, let me know about any limit on numbers you want to impose and any requirements of prospective attendees (laptop with xxx loaded, for instance).

Let me know if there's anything else that you need right now

**Comment by richardGreen** [comment]
2016-07-26

Synopsis:

This workshop will walk you through the nuts and bolts of participating in Hydra development, including:

```
• What's a CLA and why do I need one?
• Why does my code need tests (aka, why did my Pull Request get rejected)?
• What does squashing commits mean?
• How big is too big (aka, how can I make my code easier to review)?
• Where do I get help (how do all the different communication channels work — where should I try first)?
• How do I bring new developers at my institution into the Hydra community?
```

Audience: new developers, or developers or managers who will be on-boarding new developers

Attendees should have a laptop with a Git client for hands-on Git demonstrations.

**Comment by richardGreen** [comment]
Esmé and Mike Giarlo confirmed
