### ISSUE TITLE
Hydra, research data and Archivematica

### ISSUE THREAD

**Issue by lsat12357** [projecthydra-labs/hydra-connect#29]
Hydra, research data and Archivematica Notwithstanding Rick's ideas above, a couple of us in the UK are looking at Archivematica's place in a research data pipeline. Hull and York have slightly different use cases but share the desire to put research (and likely other) content through Archivematica on its way to the repository thus giving us a solid base for long-term preservation. At the time of writing (June) we are each building a proof-of-concept system and this work should be complete and demonstrable by October.

Suggested by: Richard Green
Presenter: Richard Green Julie Allinson
Format: Presentation
Audience: Developers, managers

**Comment by richardGreen** [comment]
In the UK, the Universities of York and Hull are looking at Archivematica's place in a research data pipeline.  The two universities have slightly different use cases but share the desire to put research (and likely other) content through Archivematica on its way to the repository thus giving us a solid base for long-term preservation. At the time of writing (June) we are each building a proof-of-concept system and this work should be complete and demonstrable by October.

Suggested by: Richard Green
Presenter: Richard Green Julie Allinson
Format: Presentation
Audience: All

**Comment by richardGreen** [comment]
2016-07-06  Richard registered; Julie agreed subject to funding.

**Comment by richardGreen** [comment]
8/18
1. Yes!
2. Myself and Richard Green
3. Fine with me
4. I'll discuss offline with richard
5. Noted.
Thanks!
Julie
Richard OK with recording.

**Comment by richardGreen** [comment]
In the UK, the Universities of York and Hull are looking at Archivematica's place in a research data pipeline. The two universities have slightly different use cases but share the desire to put research (and likely other) content through Archivematica on its way to the repository thus giving us a solid base for long-term preservation. We are both now in the third phase of a joint project to build proof-of-concepts to illustrate how Hydra and Archivematica can work together to manage and preserve research data. Since our project began, Jisc have launched an ambitious UK national research data shared service where are range of suppliers offer systems in different lots. Both Hydra / Fedora and Islandora / Fedora are part of the the ‘research repository’ lot of the service and the work of York and Hull has heavily informed the ‘preservation’ lot, with Archivematica one of the systems on offer. This presentation will demonstrate the proof-of-concept work done by Hull and York, and will provide an overview of the new Jisc service.
