### ISSUE TITLE
Case Study: Oregon Digital Migration from ContentDM to Hydra for digital collec...

### ISSUE THREAD

**Issue by lsat12357** [projecthydra-labs/hydra-connect#4]
Case Study: Oregon Digital Migration from ContentDM to Hydra for digital collections

Suggested by: Sheila Rabun
Presenter: Oregon Digital team (potentially including former team members?)
Format: Presentation
Audience: All

**Comment by richardGreen** [comment]
2016-07-27

Sheila

You’ll recall that this presentation, suggested by you, was adopted by the Program Committee yesterday.  I’d be very grateful if you could get me the speaker’s names and a description as soon as possible so that we can get their agreement to talk (and possibly to be recorded) as soon as possible.

**Comment by richardGreen** [comment]
Synopsis: This case study will address the initial decisions and reasons for switching to Hydra, prototyping for launch of Hydra head, metadata cleanup and asset migration, final quality review, and lessons learned.

**Comment by richardGreen** [comment]
2016-08-10 
Sheila

We urgently need these names please to make sure we don’t timetable any clashes requiring the same presenter(s) to be in more than one place at the same time!

Thanks.

Richard

**Comment by srabun** [comment]
Dear Richard and all
I am replying for Sheila Rabun

The presenters for this session (Case Study: Oregon Digital Migration from ContentDM to Hydra for digital collections)  will be:
 Julia Simic and Linda Sato from University of Oregon and
Ryan Wick and Margaret Mellinger from Oregon State University

Thank you for your patience,
Margaret

Margaret Mellinger
Director, Emerging Technologies & Services
Oregon State University Libraries & Press
121 The Valley Library, Corvallis OR 97331-4501 | (541) 737-9642

> 2016-08-10
> Sheila
> We urgently need these names please to make sure we don’t timetable any clashes requiring the same presenter(s) to be in more than one place at the same time!
> Thanks.
> Richard

**Comment by richardGreen** [comment]
2016-08-11
Julia Simic and Linda Sato from University of Oregon and 
Ryan Wick and Margaret Mellinger from Oregon State University

**Comment by richardGreen** [comment]
8/18
1.  Email back to confirm that you are still willing and able to give this session.  Yes, we are willing and able. 
2.  Confirm the names and willingness of any co-presenters.  Yes, to the names and willingness of all presenters 
3.  Indicate your willingness (or otherwise) to having your session recorded to be linked later from the Hydra wiki. Yes, we are willing to be recorded. 
4.  Check the description of your session on the wiki page for presentations, panels and breakouts.  Please feel free to deal with any omissions or errors.  The presentation description is brief, but correct – we’ll keep it. 
5.  And finally, if you haven't yet registered for Hydra Connect 2016 - now would be a good time to do so!  Bear in mind that the specially negotiated hotel rate is only available until September 6th.    I believe we are all registered.
